task_make_ics:
  chgres_cube:
    namelist:
      update_values:
        config:
          varmap_file: >
            {% if {{ workflow.CCPP_PHYS_SUITE }} in [
              "FV3_GFS_2017_gfdlmp",
              "FV3_GFS_2017_gfdlmp_regional", 
              "FV3_GFS_v16",
              "FV3_GFS_v15p2"
            ] %}
            "{{ user.PARMdir }}/ufs_utils/varmap_tables/GFSphys_var_map.txt"
            {% elif {{ workflow.CCPP_PHYS_SUITE }} in [
              "FV3_RRFS_v1beta", 
              "FV3_GFS_v15_thompson_mynn_lam3km",
              "FV3_GFS_v17_p8",
              "FV3_WoFS_v0",
              "FV3_HRRR",
              "FV3_RAP"
            ] and {{ task_get_extrn_ics.EXTRN_MDL_NAME_ICS }} in [
              "RAP", 
              "HRRR"
            ] %}
            "{{ user.PARMdir }}/ufs_utils/varmap_tables/GSDphys_var_map.txt"
            {% endif %}
task_make_lbcs:
  chgres_cube:
    namelist:
      update_values:
        config:
          varmap_file: >
            {% if {{ workflow.CCPP_PHYS_SUITE }} in [
              "FV3_GFS_2017_gfdlmp",
              "FV3_GFS_2017_gfdlmp_regional", 
              "FV3_GFS_v16",
              "FV3_GFS_v15p2"
            ] %}
            "{{ user.PARMdir }}/ufs_utils/varmap_tables/GFSphys_var_map.txt"
            {% elif {{ workflow.CCPP_PHYS_SUITE }} in [
              "FV3_RRFS_v1beta", 
              "FV3_GFS_v15_thompson_mynn_lam3km",
              "FV3_GFS_v17_p8",
              "FV3_WoFS_v0",
              "FV3_HRRR",
              "FV3_RAP"
            ] and {{ task_get_extrn_lbcs.EXTRN_MDL_NAME_LBCS }} in [
              "RAP", 
              "HRRR"
            ] %}
            "{{ user.PARMdir }}/ufs_utils/varmap_tables/GSDphys_var_map.txt"
            {% endif %}