
task_make_ics:
  chgres_cube:
    namelist:
      update_values:
        config:
          input_type: "gaussian_netcdf"
task_make_lbcs:
  chgres_cube:
    namelist:
      update_values:
        config:
          input_type: "gaussian_netcdf"
task_run_post:
  upp:
    files_to_copy:
      postxconfig-NT.txt: "{{ workflow.PARMdir }}/upp/postxconfig-NT-AQM.txt"
    namelist:
      update_values:
        nampgb:
          aqf_on: true
  output_file_labels:
    - cmaq
